# This configuration is temporary while we work on getting all unit tests to pass on PR checks

# Don't run CI for this config
trigger: none

# Run PR validation on all branches
pr:
  branches:
    include:
    - '*'

jobs:
- template: jobs/default-build.yml
  parameters:
    jobName: Windows_Build
    jobDisplayName: "Build only : Windows"
    agentOs: Windows
    buildArgs: '/p:SkipTests=true'
- template: jobs/default-build.yml
  parameters:
    jobName: macOs_Build
    jobDisplayName: "Build only : macOS"
    agentOs: macOS
    buildArgs: '/p:SkipTests=true'
- template: jobs/default-build.yml
  parameters:
    jobName: Linux_Build
    jobDisplayName: "Build only : Linux"
    agentOs: Linux
    buildArgs: '/p:SkipTests=true'
- job: Code_check
  displayName: Code check
  workspace:
    clean: all
  pool:
    vmImage: vs2017-win2016
  steps:
  - powershell: ./eng/scripts/CodeCheck.ps1 -ci
