jobs:
- template: default-build.yml
  parameters:
    jobName: 'IISIntegration'
    jobDisplayName: 'IISIntegration'
    beforeBuild:
      - powershell: "& ./src/servers/IIS/tools/UpdateIISExpressCertificate.ps1; & ./src/servers/IIS/tools/SetupTestEnvironment.ps1 Setup"
        displayName: Prepare repo
    afterBuild:
      - powershell: "& ./src/servers/IIS/tools/SetupTestEnvironment.ps1 Shutdown"
        displayName: Stop AppVerifier
        condition: always()
      - task: PublishBuildArtifacts@1
        displayName: Upload logs
        condition: eq(variables['system.pullrequest.isfork'], false)
        inputs:
          artifactName: logs
          artifactType: Container
          pathtoPublish: src/servers/IIS/artifacts/logs
    buildDirectory: src/servers/IIS
